### ISSUE TITLE
Generated lanterns have tendecy to spawn water-logged/

### ISSUE THREAD

**Issue by itsbanditodorito** [ThePoultryMan/Lanterns-Belong-On-Walls#12]
For some generated structures/features, such as supplementary's road signs/sign posts,  lanterns that generate are water logged.

This can be reproduced  by either generating a structure/feature that also generates lanterns using /place (non-vanilla command), or by using /setblock ~ ~ ~ minecraft:lantern. By using the latter, it will spawn a water logged lantern 100% of the time. Even if Lanterns Belong on Walls is the only mod present.

![image](https://user-images.githubusercontent.com/113280308/201293783-d4214de8-1170-454c-a8d7-07fabcc2ff5a.png)
![image](https://user-images.githubusercontent.com/113280308/201293912-7a82a16b-14ca-4fd5-94de-4e64a56e3a89.png)

Second image shows the lantern thinking its being placed on a wall, but there's no wall present. I'm guessing that would be why water spawns on it, so it was something to "place" on.

**Comment by TelepathicGrunt** [comment]
I keep getting reports from people about how lanterns in my structures from Repurposed Structures are spawning waterlogged since 1.18.2. I was never able to find what mod was at fault until just today when someone approached me in DM saying to might be this mod

Past issue reports: https://github.com/TelepathicGrunt/RepurposedStructures-Quilt/issues/219

The issue is this mixin is not safe (Pretty sure it's the default blockstate part): https://github.com/ThePoultryMan/Lanterns-Belong-On-Walls/blob/main/src/main/java/io/github/thepoultryman/walllanterns/mixin/WallLanternsMixin.java

Please switch to using Statement to properly adding new states to vanilla blocks without breaking other mods. They already handle all the strange edge cases and issues that comes with trying to hack in new states into vanilla blocks.
https://www.curseforge.com/minecraft/mc-mods/statement

I'm going to have to mark this mod as incompatible with mine since it is causing lanterns to spawn waterlogged in my Nether Strongholds which is a big no as the Nether should never have water blocks.
![image](https://user-images.githubusercontent.com/40846040/214973350-5ded9d66-1761-4645-b34f-5b420a7bf7ed.png)

**Comment by ThePoultryMan** [comment]
This should no longer be an issue.
