### ISSUE TITLE
Causes huge FPS drops when running on my server

### ISSUE THREAD

**Issue by ChristopherHaws** [ThePoultryMan/Lanterns-Belong-On-Walls#2]
Hey there!

This mod causes my client to have super low FPS (around 10 FPS) when this mod is installed on my server. When this mod isn't installed server side, my client runs at 120 FPS. When I play in single player with this mod, it works fine, it is only when it is installed server side that this issue happens. TPS and MSPT are both perfect though so I am not sure what is causing the low framerates. I ran a spark profile and it didn't show much of anything.

**Comment by ThePoultryMan** [comment]
I can't reproduce this locally (with only Lanterns Belong on Walls). To debug this further, I need the server and client logs.

**Comment by ChristopherHaws** [comment]
@ThePoultryMan I will try to get that for you. If I remember correctly, nothing specific was logged. I figured out that this mod was the issue by process of elimination. 

In the meantime, here is my git repo which contains all the mods I use (excluding this one): https://github.com/ChristopherHaws/minecraft-craftersmc-modpack

**Comment by ThePoultryMan** [comment]
Using your latest commit on both the client and server, and adding the latest version of the mod (1.2.0) from my local dev environment, I'm unable to reproduce. The server was missing Better Recipe Book, Server Translations, Inspecio, and LambDynamicLights. I was running the server locally, and I used `localHost` to connect.

When this mod first started, this was caused by an outdated mod in the server I used to test the mod. Sadly, I don't know which one(s) caused the lag because I updated all the mods at once. My advice would be to update all the mods, and try again.
