### ISSUE TITLE
Connecting to vanilla 1.18 server causes some blocks to display wrong

### ISSUE THREAD

**Issue by TheSabotender** [ThePoultryMan/Lanterns-Belong-On-Walls#7]
I have this mod installed locally, when connecting to a vanilla 1.19 server, some blocks are replaced:

![lanternbug](https://user-images.githubusercontent.com/12509732/180826493-a41c107c-4671-4e68-a3a3-f0b35cb240d3.png)

In the screenshot you can see Mud becoming leafs, Dripstone becoming copper blocks, and at the edge of the picture a Composter becoming Water

**Comment by ThePoultryMan** [comment]
This seems to happen when the client has the mod, but the server doesn't. My guess is that because the client has an extra blockstate for the lantern block, but the server doesn't, things will get messed up. If my guess is right, then I don't think there is a way I can fix this issue. However, I will mess around and see if there is anything that I can do to fix this.

In the meantime, I will try to add a warning when this bug could happen. This warning will inform the user that they should remove the mod of they could experience "severe issues."

**Comment by mmmmmabil** [comment]
not mod related but u might want to look into polymc 
its a launcher that lets u have seperate instances with their own mod and saves

**Comment by ThePoultryMan** [comment]
Since the implementation of Statement, this should not happen. I'll do some testing when I have time to confirm that this is fixed.

**Comment by ryleu** [comment]
@ThePoultryMan this should also be applied to the 1.20 branch as it messes all of the blockstates up in large modpacks.

**Comment by ThePoultryMan** [comment]
This issue no longer seems to happen since integrating statement.
